name: Build versioned imag
on:
  push:
    tags:
      - "v*"
jobs:
  docker:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ruigouveiamaciel --password-stdin
      - name: Docker build
        run: docker build -t docker.pkg.github.com/ruigouveiamaciel/gdocs/gdocs:${GITHUB_REF#refs/tags/} .
      - name: Docker push tag latest
        run: docker push docker.pkg.github.com/ruigouveiamaciel/gdocs/gdocs:${GITHUB_REF#refs/tags/}