name: Build commit image
on: pull_request
jobs:
  docker:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ruigouveiamaciel --password-stdin
      - name: Docker build
        run: docker build -t docker.pkg.github.com/ruigouveiamaciel/gdocs/staging:${GITHUB_REF#refs/tags/} .
      - name: Docker push tag latest
        run: docker push docker.pkg.github.com/ruigouveiamaciel/gdocs/staging:${GITHUB_REF#refs/tags/}
      - name: Notify of Registry URL
          uses: unsplash/comment-on-pr@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            msg: "The latest commit built at: docker.pkg.github.com/ruigouveiamaciel/gdocs/staging:${{github.sha}}"